### ISSUE TITLE
import not working on windows because of the banner

### ISSUE THREAD

**Issue by nhuet** [Alexander-Nasuta/graph-jsp-env#3]
Hi, i tried your library on different plateform and discovered that the banner prevented me to import it on windows because of encoding issues:
```
tests\solvers\python\test_gnn_sb3.py:7: in <module>
    from graph_jsp_env.disjunctive_graph_jsp_env import DisjunctiveGraphJspEnv
C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\site-packages\graph_jsp_env\disjunctive_graph_jsp_env.py:12: in <module>
    from graph_jsp_env.disjunctive_graph_jsp_visualizer import DisjunctiveGraphJspVisualizer
C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\site-packages\graph_jsp_env\disjunctive_graph_jsp_visualizer.py:19: in <module>
    from graph_jsp_env.disjunctive_graph_logger import log
C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\site-packages\graph_jsp_env\disjunctive_graph_logger.py:11: in <module>
    print(small_banner if w < 140 else big_banner)
C:\hostedtoolcache\windows\Python\3.12.7\x64\Lib\encodings\cp1252.py:19: in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
E   UnicodeEncodeError: 'charmap' codec can't encode characters in position 233-237: character maps to <undefined>
```

**Comment by Alexander-Nasuta** [comment]
Hi, could you share a minimal code snippet, so I can reproduce it? I'll try to reproduce it on a windows machine of mine next week.

**Comment by nhuet** [comment]
Very simple :) :
```
from graph_jsp_env.disjunctive_graph_jsp_env import DisjunctiveGraphJspEnv
```

It crashes when trying to display the banner.
Tested on windows-latest github runner.

**Comment by Alexander-Nasuta** [comment]
I tried to reproduce the issue, but unfortunately, I couldn't replicate the error on my side. I tested the library on a Windows 11 machine using both PyCharm and PowerShell. Everything worked as expected. To ensure further accuracy, I also updated the license date to trigger the GitHub workflow, which tests the environment on both Linux and Windows, including the latest GitHub Windows runner, and no errors were encountered.

Could you provide more details about your system setup? Specifically:

- The version of Windows you're using.
- Your locale and default encoding settings.
- Any additional settings or configurations in your environment that might impact encoding.

This information will help narrow down the cause of the issue.

Thank you!

Best regards,

Alexander


![graph-jsp-windows-banner-screenshot](https://github.com/user-attachments/assets/6636887f-b6e2-4315-bde4-79cbca59c933)
<img width="1481" alt="github-runner-screenshot" src="https://github.com/user-attachments/assets/5fe94fbe-7318-44ab-8f14-965fc7d1f226">

**Comment by nhuet** [comment]
Actually same error with powershell: https://github.com/nhuet/code-testing/actions/runs/12115735694/job/33774698036

**Comment by Alexander-Nasuta** [comment]
![ScreenshotBannerChar](https://github.com/user-attachments/assets/423f08eb-21a9-4eee-9f24-5fd6d1c0da75)

Hi,

it seems that the shell does'nt know the unicode block characters. The color coding seems to work fine. I update you once I know more. Maybe installing a nerd font or so could resolve this issue.

**Comment by Alexander-Nasuta** [comment]
Hi nhuet,

To resolve the issue, please add the following step to your workflow:

`- name: Set PYTHONIOENCODING to UTF-8
  run: |
    echo "PYTHONIOENCODING=UTF-8" >> $GITHUB_ENV
`
This step ensures Python uses UTF-8 for all input and output operations, which should prevent encoding-related errors.

For reference, here’s the workflow file I used to test the solution:

https://github.com/Alexander-Nasuta/code-testing/actions/runs/12195039070/workflow

Additionally, here are a few screenshots for further clarification:

![runner](https://github.com/user-attachments/assets/9982dd03-9a11-484e-8d12-5a7e67d03906)
![workflow](https://github.com/user-attachments/assets/0cfef1d2-242e-4b04-af3f-d5b4c33ab495)


Let me know if you encounter any issues or need further assistance!
